# Generated by Django 5.0.1 on 2024-02-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='sensor',
            field=models.IntegerField(default=None),
        ),
    ]
